fixes:
  - "::apps/-- the project name --/"

flags:
  astarte_appengine_api:
    paths:
      - apps/astarte_appengine_api/
  astarte_data_updater_plant:
    paths:
      - apps/astarte_data_updater_plant/
  astarte_trigger_engine:
    paths:
      - apps/astarte_trigger_engine/
  astarte_pairing:
    paths:
      - apps/astarte_pairing/
  astarte_pairing_api:
    paths:
      - apps/astarte_pairing_api/
  astarte_realm_management:
    paths:
      - apps/astarte_realm_management/
  astarte_realm_management_api:
    paths:
      - apps/astarte_realm_management_api/
  astarte_housekeeping:
    paths:
      - apps/astarte_housekeeping/
  astarte_housekeeping_api:
    paths:
      - apps/astarte_housekeeping_api/
