version: '2'
services:
  # Astarte main services
  astarte-standalone:
    image: astarte/astarte:0.10-snapshot
    env_file:
     - ./compose.env
    environment:
      ASTARTE_CASSANDRA_NODES: "cassandra:9042"
      APPENGINE_API_MQTT_HOST: "vernemq"
      APPENGINE_API_MQTT_USERNAME: "appengine"
      APPENGINE_API_MQTT_PASSWORD: "appengine"
      APPENGINE_API_ROOMS_AMQP_CLIENT_HOST: "rabbitmq"
      DATA_UPDATER_PLANT_AMQP_CONSUMER_HOST: "rabbitmq"
      DATA_UPDATER_PLANT_AMQP_PRODUCER_HOST: "rabbitmq"
      DATA_UPDATER_PLANT_AMQP_PRODUCER_PORT: "5672"
      DATA_UPDATER_PLANT_AMQP_PRODUCER_USERNAME: "guest"
      DATA_UPDATER_PLANT_AMQP_PRODUCER_PASSWORD: "guest"
      DATA_UPDATER_PLANT_AMQP_PRODUCER_VIRTUAL_HOST: "/"
      TRIGGER_ENGINE_AMQP_CONSUMER_HOST: "rabbitmq"
      ASTARTE_RPC_AMQP_CONNECTION_HOST: "rabbitmq"
      HOUSEKEEPING_API_JWT_PUBLIC_KEY_PATH: "/keys/housekeeping.pub"
      PAIRING_CFSSL_URL: "http://cfssl:8080"
    ports:
      - "4000:4000"
      - "4001:4001"
      - "4002:4002"
      - "4003:4003"
    volumes:
      - ./compose/astarte-keys/housekeeping.pub:/keys/housekeeping.pub
    depends_on:
      - "rabbitmq"
      - "cassandra"
      - "vernemq"
    # We don't wait for anything, as supervisord will restart stuff until it hits.

  astarte-dashboard:
    image: astarte/astarte-dashboard:0.10-snapshot
    ports:
      - "4040:80"
    volumes:
      - ./compose/astarte-dashboard/config.json:/usr/share/nginx/html/user-config/config.json
    depends_on:
      - "astarte-standalone"

  astarte-grafana:
    image: astarte/grafana:0.10-snapshot
    ports:
      - "3000:3000"
    depends_on:
      - "astarte-standalone"

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3.7
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  # CFSSL
  postgresql:
    image: postgres:9.6
    environment:
      POSTGRES_USER: "astarte"
      POSTGRES_PASSWORD: "astarte"
    volumes:
      - postgresql-data:/var/lib/postgresql/data
  cfssl:
    image: astarte/cfssl
    depends_on:
      - "postgresql"
    volumes:
      - ./compose/cfssl-config:/config
      - cfssl-data:/data
    # Ensure we wait for pg
    command: wait-for postgresql:5432 -t 90 -- cfssl serve -address=0.0.0.0 -ca=/data/ca.pem -ca-key=/data/ca-key.pem -port=8080 -config=/etc/cfssl/ca_root_config.json -db-config=/etc/cfssl/db_config.json
    # Restart if we fail
    restart: on-failure

  # Cassandra
  cassandra:
    image: cassandra:3.11
    volumes:
      - cassandra-data:/var/lib/cassandra

  # VerneMQ
  vernemq:
    image: astarte/vernemq:0.10-snapshot
    env_file:
     - ./compose.env
    environment:
      DOCKER_VERNEMQ_LISTENER__SSL__DEFAULT__CAFILE: "/opt/vernemq/etc/ca.pem"
      DOCKER_VERNEMQ_LISTENER__SSL__DEFAULT__CERTFILE: "/opt/vernemq/etc/cert.pem"
      DOCKER_VERNEMQ_LISTENER__SSL__DEFAULT__KEYFILE: "/opt/vernemq/etc/privkey.pem"
      DOCKER_VERNEMQ_ASTARTE_VMQ_PLUGIN__AMQP__USERNAME: "guest"
      DOCKER_VERNEMQ_ASTARTE_VMQ_PLUGIN__AMQP__PASSWORD: "guest"
      DOCKER_VERNEMQ_ASTARTE_VMQ_PLUGIN__AMQP__HOST: "rabbitmq"
      DOCKER_VERNEMQ_USER_appengine: "appengine"
      CFSSL_URL: "http://cfssl:8080"
    ports:
      # 1883 is used internally and isn't exposed
      # Used with HAProxy only
      - "1885:1885"
      # Used with SSL Listener only
      - "8883:8883"
      # You can comment this out if you don't need Let's Encrypt
      - "80:80"
    volumes:
      - vernemq-data:/opt/vernemq/data
      - ./compose/vernemq-certs:/etc/ssl/vernemq-certs
    depends_on:
      - "cfssl"
      - "rabbitmq"
    # Ensure we wait for rabbit and cfssl
    command: wait-for rabbitmq:5672 -t 90 -- wait-for cfssl:8080 -t 90 -- /opt/vernemq/bin/vernemq.sh
    # Restart if we fail
    restart: on-failure
volumes:
  rabbitmq-data:
  postgresql-data:
  cassandra-data:
  vernemq-data:
