name: Test Container Builds

on:
  pull_request:
    paths:
    - '**/Dockerfile'
    - '**/entrypoint.sh'
    - '.github/pr-container-build-workflow.yaml'

jobs:
  test-build-container:
    name: Test Container Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [astarte_appengine_api, astarte_data_updater_plant, astarte_trigger_engine, astarte_pairing, astarte_pairing_api, astarte_realm_management, astarte_realm_management_api, astarte_housekeeping, astarte_housekeeping_api]
    steps:
    - uses: actions/checkout@v1
    - name: Building Docker Image
      env:
        CONTAINER_IMAGE_NAME: gh_actions_test
      working-directory: ./apps/${{ matrix.app }}
      run: docker build -t $CONTAINER_IMAGE_NAME:ci-test .
